// Jam.swift
// Statter
//
// This file auto-generated by treemaker, do not edit
//

import Foundation
public struct Jam<P:PathSpecified> : PathNodeId, Identifiable {
    public var parent: P
    public var id: Int? { Int.from(component: statePath.last)?.1 }
    public let statePath: StatePath
    @Leaf public var walltimeStart: Int?

    public init(parent: P, jam: Int) {
        self.parent = parent
        statePath = parent.adding(.number("Jam", param: jam))

        _walltimeStart = parent.leaf("WalltimeStart")
        _walltimeStart.parentPath = statePath
    }
    public init(parent: P, statePath: StatePath) {
        self.parent = parent
        self.statePath = statePath
        _walltimeStart = parent.leaf("WalltimeStart")
        _walltimeStart.parentPath = statePath
    }
}
extension Period {
    public func jam(_ jam: Int) -> Jam<Period> { .init(parent: self, jam: jam) }
}
extension Game {
    public func jam(_ jam: Int) -> Jam<Game> { .init(parent: self, jam: jam) }
}
