// PreparedSkater.swift
// Statter
//
// This file auto-generated by treemaker, do not edit
//

import Foundation
public struct PreparedSkater : PathNodeId, Identifiable {
    public var parent: PreparedTeam
    public var id: StatePath { statePath }
    public let statePath: StatePath
    @ImmutableLeaf public var skaterId: UUID?

    @ImmutableLeaf public var readonly: Bool?

    @Leaf public var name: String?

    @ImmutableLeaf public var number: String?

    @Leaf public var rosterNumber: String?

    @Leaf public var flags: Skater.Flags?

    @Leaf public var pronouns: String?

    public init(parent: PreparedTeam, _ key: UUID) {
        self.parent = parent
        statePath = parent.adding(.id("PreparedSkater", id: key))

        _skaterId = parent.leaf("skaterId").immutable
        _readonly = parent.leaf("Readonly").immutable
        _name = parent.leaf("Name")
        _number = parent.leaf("Number").immutable
        _rosterNumber = parent.leaf("RosterNumber")
        _flags = parent.leaf("Flags")
        _pronouns = parent.leaf("Pronouns")
        _skaterId.parentPath = statePath
        _readonly.parentPath = statePath
        _name.parentPath = statePath
        _number.parentPath = statePath
        _rosterNumber.parentPath = statePath
        _flags.parentPath = statePath
        _pronouns.parentPath = statePath
    }
    public init(parent: PreparedTeam, statePath: StatePath) {
        self.parent = parent
        self.statePath = statePath
        _skaterId = parent.leaf("skaterId").immutable
        _readonly = parent.leaf("Readonly").immutable
        _name = parent.leaf("Name")
        _number = parent.leaf("Number").immutable
        _rosterNumber = parent.leaf("RosterNumber")
        _flags = parent.leaf("Flags")
        _pronouns = parent.leaf("Pronouns")
        _skaterId.parentPath = statePath
        _readonly.parentPath = statePath
        _name.parentPath = statePath
        _number.parentPath = statePath
        _rosterNumber.parentPath = statePath
        _flags.parentPath = statePath
        _pronouns.parentPath = statePath
    }
}
extension PreparedTeam {
    public func skater(_ key: UUID) -> PreparedSkater { .init(parent: self, key) }
}
