// Rule.swift
// Statter
//
// This file auto-generated by treemaker, do not edit
//

import Foundation
public struct Rule : PathNode {
    public var parent: Game
    public let statePath: StatePath
    public init(parent: Game) {
        self.parent = parent
        statePath = parent.adding("Rule")

    }
    public init(parent: Game, statePath: StatePath) {
        self.parent = parent
        self.statePath = statePath
    }
}
extension Game {
    public var rule: Rule { .init(parent: self) }
}
