// TeamJam.swift
// Statter
//
// This file auto-generated by treemaker, do not edit
//

import Foundation
public struct TeamJam<P:PathSpecified> : PathNode {
    public var parent: Jam<P>
    public let statePath: StatePath
    public init(parent: Jam<P>, team: Int) {
        self.parent = parent
        statePath = parent.adding(.number("TeamJam", param: team))

    }
    public init(parent: Jam<P>, statePath: StatePath) {
        self.parent = parent
        self.statePath = statePath
    }
}
extension Jam {
    public func teamJam(_ team: Int) -> TeamJam<P> { .init(parent: self, team: team) }
}
